version: 2.1
orbs:
  codecov: codecov/codecov@5.0.3

executors:
  java21:
    docker:
      - image: cimg/openjdk:21.0.2

jobs:
  build:
    executor: java21
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn test
      - codecov/upload

workflows:
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master