version: 2.1
orbs:
  codecov: codecov/codecov@5.0.3

executors:
  java21:
    docker:
      - image: cimg/openjdk:21.0.2

jobs:
  build:
    executor: java21
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn test
      - codecov/upload
  check:
    executor: java21
    steps:
      - checkout
      - run: mvn checkstyle:check
      - run: sh badge-script.sh target/checkstyle-result.xml
      - store_artifacts:
          path: target/checkstyle-result.xml
      - store_artifacts:
          path: checkstyle-badge.svg
      - run: 'curl -X PUT -H "Content-Type:image/svg+xml" --data-binary @checkstyle-badge.svg "https://storage.googleapis.com/alerex-techniques-de-test/checkstyle-badge.svg"'
  docs-build:
    executor: java21
    steps:
      - checkout
      - run: mvn javadoc:javadoc
      - store_artifacts:
          path: target/reports
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run: mkdir temp && cd temp
      - run: 'curl -s -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/SireAlerex/ceri-m1-techniques-de-test/latest/artifacts | grep -o -E "https://([^"]*)"   | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -'
      - run: cd ../
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist temp

workflows:
  build_and_test:
    jobs:
      - check:
        filters:
          branches:
            only:
              - master
      - build:
        filters:
          branches:
            only:
              - master
      - docs-build:
        filters:
          branches:
            only:
              - master
