version: 2.1
orbs:
  codecov: codecov/codecov@5.0.3
  gcp-cli: circleci/gcp-cli@3.2.2

executors:
  java21:
    docker:
      - image: cimg/openjdk:21.0.2

jobs:
  use-gcp:
    executor: gcp-cli/default
    steps:
      - gcp-cli/setup:
          version: 404.0.0
  build:
    executor: java21
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn test
      - codecov/upload
  check:
    executor: java21
    steps:
      - checkout
      - run: mvn checkstyle:check
      - run: sh badge-script.sh
      - run: gsutil --version
      - store_artifacts:
          path: target/checkstyle-result.xml
      - store_artifacts:
          path: checkstyle-badge.svg

workflows:
  build_and_test:
    jobs:
      - use-gcp:
        filters:
          branches:
            only:
              - master
      - check:
        filters:
          branches:
            only:
              - master
      - build:
        filters:
          branches:
            only:
              - master
