version: 2.1
orbs:
  codecov: codecov/codecov@5.0.3

executors:
  java21:
    docker:
      - image: cimg/openjdk:21.0.2

jobs:
  build:
    executor: java21
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn test
      - codecov/upload
  check:
    executor: java21
    steps:
      - checkout
      - run: mvn checkstyle:check
      - run: sh badge-script.sh
      - store_artifacts:
          path: target/checkstyle-result.xml
      - store_artifacts:
          path: checkstyle-badge.svg
      - run: curl -X PUT --data-binary @checkstyle-badge.svg "https://storage.googleapis.com/alerex-techniques-de-test/checkstyle-badge.svg"
      - run: cat "bla" | README.md

workflows:
  build_and_test:
    jobs:
      - check:
        filters:
          branches:
            only:
              - master
      - build:
        filters:
          branches:
            only:
              - master
